# Generated by Django 4.0 on 2024-05-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_externos_nombre_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externos',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
