# Generated by Django 4.0 on 2024-05-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_externos_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='externos',
            name='id_general',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='externos',
            name='dni',
            field=models.CharField(max_length=15),
        ),
    ]
