# Generated by Django 4.0 on 2024-06-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_externos_id_general_alter_externos_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externos',
            name='id_general',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
