# Generated by Django 4.2.13 on 2024-07-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_externos_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
