# Generated by Django 4.2.14 on 2024-07-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=20)),
                ('IDconexion', models.CharField(max_length=10, unique=True)),
                ('Peso', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=10)),
            ],
        ),
    ]
