# Generated by Django 4.0 on 2024-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_importarasistenciadetalle_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuarioapp',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Embarque', 'Embarque'), ('Calidad', 'Calidad'), ('Recursos', 'Recursos')], default='Administrador', max_length=25),
        ),
    ]
