# Generated by Django 4.0 on 2024-11-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_importarasistenciadetalle_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importarasistenciadetalle',
            name='linea',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
